### ISSUE TITLE
[AZ-04 Azure Core Services] Feedback request

### ISSUE THREAD

**Issue by MJLippai** [techgrounds/cloud-6-repo-MJLippai#10]
# Feedback Request [[AZ-04 Azure Core Services]]
Permalink naar bestand: [LINK](https://github.com/techgrounds/cloud-6-repo-MJLippai/blob/main/02_Cloud_1/AZ-04%20Azure%20Core%20Services.md)

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?
```

**Comment by P03KI** [comment]
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg? _Ja_
- Is de samenvatting in eigen woorden geschreven? _Ja_
- Mist er cruciale informatie in de samenvatting? _Nee_
- Is de beschrijving duidelijk genoeg? _Ja_

De opsomming is goed maar de relatie tussen de genoemde voorbeelden kan overlappen. Misschien dat je het voorbeeld duidelijker uit kan lichten? 

## Key Terms
- Missen er sleutelwoorden? _Nee_
- Zijn de sleutelwoorden goed uitgelegd? _Ja/NVT_

## Bronnen
- Zijn bronnen vernoemd? _Ja. Bronnen staan wel allemaal op 1 lijn_
- Zijn de genoemde bronnen juist? _Ja_

## Opdracht
- Is het resultaat correct? _NVT_
