### ISSUE TITLE
[AZ-18 Azure App Service] Feedback request

### ISSUE THREAD

**Issue by MJLippai** [techgrounds/cloud-6-repo-MJLippai#19]
# Feedback Request [AZ-18 Azure App Service]
Permalink naar bestand: [AZ-18 Azure App Service](https://github.com/techgrounds/cloud-6-repo-MJLippai/blob/main/04_Cloud_3/AZ-18%20App%20Service.md)

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?
```

**Comment by henkvanderduim** [comment]
Goede samenvatting. De App Service komt aardig overeen met de vergelijkbare Beanstalk op AWS.
Een mindmap (Top!) en een overzicht wanneer de App Service kunt gebruiken (flowchart).

Key-terms zijn aanwezig en geven informatie.

De bronnen die je gebruikt hebt zijn genoemd. De bronnen zijn van Microsoft, dus ik neem aan dat ze juist zijn.

**Comment by NederLANA** [comment]
## Samenvatting
How is this different than Azure Functions or other code deployment services? When would you use App Service?

## Key Terms
The key terms are a bit more in depth and seem to indicate that Function is a subset of App Service. Perhaps some of this material can be integrated in your main Topic
