### ISSUE TITLE
NL

### ISSUE THREAD

**Issue by P03KI** [techgrounds/cloud-6-repo-MJLippai#2]
https://github.com/techgrounds/cloud-6-repo-MJLippai/blob/bd9b4404f07e465f57ff31f58c66ef639e47bd51/README.md?plain=1#L3

"Hier volg je de vooruitgaan gedurende mijn traject om Cloud Engineer te worden"

--> vooruitgang

**Comment by MJLippai** [comment]
Corrected! Thanks!
