### ISSUE TITLE
[AZ-19 Content Delivery Service] Feedback request

### ISSUE THREAD

**Issue by MJLippai** [techgrounds/cloud-6-repo-MJLippai#20]
# Feedback Request [AZ-19 Content Delivery Service]
Permalink naar bestand: [LINK](https://github.com/techgrounds/cloud-6-repo-MJLippai/blob/main/04_Cloud_3/AZ-19%20Content%20Delivery%20Network%20(CDN)%20.md)

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?
```

**Comment by henkvanderduim** [comment]
Mooie en duidelijke samenvatting.

Je hebt een key term en die kort beschreven.

De bron is aanwezig en aangezien het van Microsoft afkomstig is zal deze juist zijn.

**Comment by NederLANA** [comment]
## Samenvatting
De beschrijving is duidelijk, vooral met de beeld. 
Maar wat is de vergelijking met andere caching services van Azure?

## Key Terms
je kun je key terms wijzen precies naar de key term op jouw beschrijvingen pagina.
bijf:  [Key term]geenspatie(/beschrijvingen.md#key-term)
let op dat dat werk zolangs als je key term is markeddown als een header met de #, of ##, of ###  Key term

## Bronnen
Vernoemd bronnen goed
