### ISSUE TITLE
[AZ-21 Azure Files] Feedback request

### ISSUE THREAD

**Issue by MJLippai** [techgrounds/cloud-6-repo-MJLippai#22]
# Feedback Request [AZ-21 Azure Files]
Permalink naar bestand: [LINK](https://github.com/techgrounds/cloud-6-repo-MJLippai/blob/main/04_Cloud_3/AZ-21%20Azure%20Files.md)

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?
```

**Comment by henkvanderduim** [comment]
Duidelijke samenvatting van wat Azure Files is.
Komt behoorlijk overeen met EFS van Amazon.

Je bronnen heb je gehaald bij Microsoft, die zijn goed.

Je hebt een opdracht uitgevoerd.
