### ISSUE TITLE
[AZ-24 Azure Functions] Feedback request

### ISSUE THREAD

**Issue by MJLippai** [techgrounds/cloud-6-repo-MJLippai#25]
# Feedback Request [AZ-24 Azure Functions]
Permalink naar bestand: [LINK](https://github.com/techgrounds/cloud-6-repo-MJLippai/blob/main/04_Cloud_3/AZ-24%20Azure%20Functions.md)

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?
```

**Comment by henkvanderduim** [comment]
Je hebt Azure Functions duidelijk en bondig beschreven. 

Je hebt je key term benoemd en beschreven.

De bronnen die je hebt gebruikt zijn ook benoemd.

En je hebt een functie gemaakt.
