### ISSUE TITLE
[AZ-25 Event Grid + Queue Storage + Service Bus] Feedback request

### ISSUE THREAD

**Issue by MJLippai** [techgrounds/cloud-6-repo-MJLippai#26]
# Feedback Request [AZ-25 Event Grid + Queue Storage + Service Bus]
Permalink naar bestand: [LINK](https://github.com/techgrounds/cloud-6-repo-MJLippai/blob/main/04_Cloud_3/AZ-25%20Event%20Grid%20%2B%20Queue%20Storage%20%2B%20Service%20Bus.md)

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?
```

**Comment by henkvanderduim** [comment]
De beschrijving van Event Grid, Queue Storage en Service bus is kort en bondig. De verdieping is zoals gewoonlijk te vinden in de bronnen (die van Microsoft zijn).

De opdracht die je met Event Grid hebt uitgewerkt is goed te volgen via de screenshots.
