### ISSUE TITLE
[AZ-27 Azure Support Plans] Feedback request

### ISSUE THREAD

**Issue by MJLippai** [techgrounds/cloud-6-repo-MJLippai#28]
# Feedback Request [AZ Azure Support Plans] 
Permalink naar bestand: [LINK](https://github.com/techgrounds/cloud-6-repo-MJLippai/blob/main/05_Cloud_4/AZ-27%20Azure%20Support%20Plans.md)

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?
```

**Comment by NederLANA** [comment]
Oh wow, looks like there's  not a lot of support provided until the Enterprise level at $1k/mo. On the other hand, at AWS, these full featured support services do not even kick in until you pay $5000+!
