### ISSUE TITLE
Feedback request [TESTING: Global infrastructure]

### ISSUE THREAD

**Issue by NederLANA** [techgrounds/cloud-6-repo-MJLippai#3]
This extra button creates a different workflow. On this, I would click on your feedback request and do nothing further.

But on the drive file, it says I would create this issue in my own repository, and then send the issue link to you! Do you understand that to? That is less useful, because then I had to use slack to send that issue link to my teammates.

So when I make a feedback request here, am I asking you for a feedback to my own permalink?

# Feedback Request [Global Infrastructure]
Permalink naar bestand: [https://github.com/techgrounds/cloud-6-repo-NederLANA/blob/dfdeb138a68643a73e6951952187c4661e152c1e/02_Cloud_1/01-global-infrastructure.md]

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?
```
Deel de link van de issue met je groepsgenoten.

**Comment by MJLippai** [comment]
Test3
