### ISSUE TITLE
[AZ-30 Azure Activity Log] Feedback request

### ISSUE THREAD

**Issue by MJLippai** [techgrounds/cloud-6-repo-MJLippai#31]
# Feedback Request [AZ-30 Azure Activity Log]
Permalink naar bestand: [LINK](https://github.com/techgrounds/cloud-6-repo-MJLippai/blob/main/05_Cloud_4/AZ-30%20Azure%20Activity%20Log.md)

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?
```

**Comment by NederLANA** [comment]
Very nice. You explained here how long the log is for, and how to access the controls.
You also mentioned some services that can be integrated with this service, but perhaps you could also do a quick comparison of the differences/distinctions between this and the other similar services.
