### ISSUE TITLE
[AZ-32 Azure Monitor] Feedback request

### ISSUE THREAD

**Issue by MJLippai** [techgrounds/cloud-6-repo-MJLippai#33]
# Feedback Request [AZ-32 Azure Monitor]
Permalink naar bestand: [LINK](https://github.com/techgrounds/cloud-6-repo-MJLippai/blob/main/05_Cloud_4/AZ-32%20Azure%20Monitor.md)

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?
```

**Comment by NederLANA** [comment]
What is the difference between this and Acitivity Log? Do either of these services allow you to automatically fix issues that are identified?
In AWS, we have one service that is more geared towards auditing/compliance, and one more for monitoring health of the infrastructure. And one that actually not just logs, but also triggers SQS message, which in turn could trigger an automated service to remedy the problem.
