### ISSUE TITLE
Broken image link

### ISSUE THREAD

**Issue by TGF-CM** [techgrounds/cloud-6-repo-MJLippai#47]
https://github.com/techgrounds/cloud-6-repo-MJLippai/blob/bfa183bc99b1638146c7a61f798811ae1bf5fe6b/09_Project_01/Version_1/Documentation/Implementation/Design.md?plain=1#L17

Ook de tweede afbeelding is niet zichtbaar.  
Je had beter gebruik kunnen maken van een `git tag` en mij je repo op die tag kunnen delen: https://git-scm.com/book/en/v2/Git-Basics-Tagging

https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases

**Comment by MJLippai** [comment]
Fixed!
