### ISSUE TITLE
Codeblocks voor lijsten

### ISSUE THREAD

**Issue by TGF-CM** [techgrounds/cloud-6-repo-MJLippai#48]
Het gebruik van drie whitespaces en meer (`   `) maakt een codeblock in de rendering. Dit maakt je lijsten niet echt leesbaar.

![image](https://user-images.githubusercontent.com/72914015/156338510-516a68a2-26a1-4c83-be99-f2a310382c9b.png)

Haal de extra spaties aan het begin van de zin weg en je zal een normale lijst krijgen.

**Comment by MJLippai** [comment]
Fixed!
