### ISSUE TITLE
[AZ-03 Advantages van de cloud.md] Feedback request

### ISSUE THREAD

**Issue by MJLippai** [techgrounds/cloud-6-repo-MJLippai#9]
# Feedback Request [AZ-03 Advantages van de cloud.md]
Permalink naar bestand: [LINK](https://github.com/techgrounds/cloud-6-repo-MJLippai/blob/main/02_Cloud_1/AZ-03%20Advantages%20van%20de%20cloud.md)

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?
```

**Comment by P03KI** [comment]
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?  _Ja_
- Is de samenvatting in eigen woorden geschreven? _Gedeeltelijk_
- Mist er cruciale informatie in de samenvatting? _Nee_
- Is de beschrijving duidelijk genoeg? _Ja_

## Key Terms
- Missen er sleutelwoorden? _Nee_
- Zijn de sleutelwoorden goed uitgelegd? _Ja_

## Bronnen
- Zijn bronnen vernoemd? _Ja_
- Zijn de genoemde bronnen juist? _Ja_

## Opdracht
- Is het resultaat correct? Duidelijk omschreven. Wellicht dat je er nog een keer overheen kan kijken voor de grammatica of met een spell-check.
